#!/usr/bin/env python3
"""
Fetches model pricing from OpenRouter and generates a static pricing table.
Run at build time: `python scripts/fetch_pricing.py`

Falls back to the last committed version if the fetch fails.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

OPENROUTER_API = "https://openrouter.ai/api/v1/models"

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR.parent / "src" / "anymodel" / "generated"
OUTPUT_PATH = OUTPUT_DIR / "pricing.py"
INIT_PATH = OUTPUT_DIR / "__init__.py"


def fetch_pricing() -> dict[str, dict[str, float]]:
    """Fetch pricing data from OpenRouter API."""
    print("Fetching pricing from OpenRouter...")
    req = urllib.request.Request(OPENROUTER_API, headers={"User-Agent": "anymodel-py/build"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        if resp.status != 200:
            raise RuntimeError(f"OpenRouter API returned {resp.status}")
        data: dict[str, Any] = json.loads(resp.read().decode())

    pricing: dict[str, dict[str, float]] = {}

    for model in data.get("data", []):
        p = model.get("pricing")
        if not p or not p.get("prompt") or not p.get("completion"):
            continue

        prompt = float(p["prompt"])
        completion = float(p["completion"])

        # Skip free/zero-cost models
        if prompt == 0 and completion == 0:
            continue

        entry: dict[str, float] = {"prompt": prompt, "completion": completion}

        if p.get("input_cache_read"):
            val = float(p["input_cache_read"])
            if val != 0:
                entry["cache_read"] = val
        if p.get("input_cache_write"):
            val = float(p["input_cache_write"])
            if val != 0:
                entry["cache_write"] = val

        pricing[model["id"]] = entry

    print(f"Fetched pricing for {len(pricing)} models")
    return pricing


def generate_source(pricing: dict[str, dict[str, float]]) -> str:
    """Generate Python source for the pricing module."""
    now = datetime.now(timezone.utc).isoformat()

    entries: list[str] = []
    for model_id, entry in sorted(pricing.items()):
        parts = [f'"prompt": {entry["prompt"]!r}, "completion": {entry["completion"]!r}']
        if "cache_read" in entry:
            parts.append(f'"cache_read": {entry["cache_read"]!r}')
        if "cache_write" in entry:
            parts.append(f'"cache_write": {entry["cache_write"]!r}')
        entries.append(f'    "{model_id}": {{{", ".join(parts)}}}')

    entries_str = ",\n".join(entries)

    return f'''# Auto-generated by scripts/fetch_pricing.py — DO NOT EDIT
# Source: OpenRouter /api/v1/models
# Generated: {now}

from __future__ import annotations

from typing import Optional


# Date this pricing data was fetched
PRICING_AS_OF: str = "{now}"

# Number of models with pricing data
PRICING_MODEL_COUNT: int = {len(pricing)}

# Model pricing table keyed by OpenRouter model ID (provider/model format).
# Costs are per-token in USD.
MODEL_PRICING: dict[str, dict[str, float]] = {{
{entries_str},
}}


def get_model_pricing(model_id: str) -> Optional[dict[str, float]]:
    """
    Look up pricing for a model. Tries exact match first,
    then falls back to prefix matching for versioned models.
    """
    # Exact match
    if model_id in MODEL_PRICING:
        return MODEL_PRICING[model_id]

    # Prefix match: "openai/gpt-4o-2024-08-06" -> "openai/gpt-4o"
    for known_id, pricing in MODEL_PRICING.items():
        if model_id.startswith(known_id) or known_id.startswith(model_id):
            return pricing

    return None


def calculate_cost(
    model_id: str,
    prompt_tokens: int,
    completion_tokens: int,
) -> float:
    """Calculate the cost for a request given token counts."""
    pricing = get_model_pricing(model_id)
    if not pricing:
        return 0.0
    return (prompt_tokens * pricing["prompt"]) + (completion_tokens * pricing["completion"])
'''


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Ensure __init__.py exists
    if not INIT_PATH.exists():
        INIT_PATH.write_text("# Auto-generated pricing data — see scripts/fetch_pricing.py\n")

    try:
        pricing = fetch_pricing()
        source = generate_source(pricing)
        OUTPUT_PATH.write_text(source)
        print(f"Written to {OUTPUT_PATH}")
    except Exception as err:
        print(f"Failed to fetch pricing: {err}", file=sys.stderr)
        if OUTPUT_PATH.exists():
            print("Using existing pricing data as fallback")
        else:
            print("No fallback available — generating empty pricing table", file=sys.stderr)
            empty = generate_source({})
            OUTPUT_PATH.write_text(empty)
        # Don't fail the build
        sys.exit(0)


if __name__ == "__main__":
    main()
